spring.application.name=mappingdemo
# Connection to MySQL DB
spring.datasource.url=jdbc:mysql://localhost:3306/sa63
spring.datasource.username=root
spring.datasource.password=password1$

#Connection to H2/MSSQL Server
#spring.datasource.url=


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Session is connecting the java program to db
# false connection to the DB pool conserved
spring.jpa.open-in-view=false

# Force Spring Boot to run initialization scripts for external databases like MySQL
spring.sql.init.mode=always
# Defer data.sql execution until AFTER Hibernate creates the tables
spring.jpa.defer-datasource-initialization=true

