spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/backend?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password1$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop

#H2 schema.sql (DDL) data.sql (DML)
#MySQL one data.sql (DDL+DML)
spring.sql.init.mode=always
#spring.sql.init.mode=never
# Forces Hibernate DDL to run before data.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
#This property is to print the SQL commans in console 
#Needed Model Mapping + JPA
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server.port=8080
